project_id = "mkmrasgbrhwtycwpdtke"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = true

[functions.transcribe-speech]
verify_jwt = false

[functions.teach-mentiora-feedback]
verify_jwt = false