project_id = "mkmrasgbrhwtycwpdtke"

[functions.seed-sat-questions]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = true