project_id = "mkmrasgbrhwtycwpdtke"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = true

[functions.ai-teacher-feedback]
verify_jwt = false